spring:
  ai:
    ollama:
      base-url: http://localhost:9999  # несуществующий адрес
      enabled: false
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_ai
    username: postgres
    password: password

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
