server:
  port: 8081

spring:
  application:
    name: meal-service
  profiles:
    active: dev  # по умолчанию

  ai:
#    vectorstore:
#      store-type: pgvector      # ← обязательно
#      pgvector:
#        table-name: chat_memory        # имя таблицы
#        initialize-schema: true        # создаст колонки, если их нет
#        dimension: 768                 # под embed-модель (nomic-embed-text = 768)
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
      embedding:
        model: nomic-embed-text
      chat:
        model: llama3:latest
        temperature: 0.2

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger
    operations-sorter: alpha
